function showMessage(){
    echo "*************"
    echo "************* $1"
    echo "*************"
}

showMessage "Let's init a new custom theme based on ScandiPWA"

CWD=`pwd`
THEME_NAMESPACE=Scandiweb
THEME_NAME=pwa
CUSTOM_THEME_PATH=app/design/frontend/$THEME_NAMESPACE/$THEME_NAME
BASE_THEME_URL=git@github.com:scandipwa/base-theme.git
BASE_THEME_BRANCH=2.x-stable

git init

showMessage "Clone base-theme as base for our custom theme"
git clone -b $BASE_THEME_BRANCH --depth=1 $BASE_THEME_URL $CUSTOM_THEME_PATH
git add $CUSTOM_THEME_PATH

rm -rf $CUSTOM_THEME_PATH/.git
rm -rf $CUSTOM_THEME_PATH/.github
rm -rf $CUSTOM_THEME_PATH/.vscode
rm -rf $CUSTOM_THEME_PATH/.all-contributorsrc
rm -rf $CUSTOM_THEME_PATH/.babelrc
rm -rf $CUSTOM_THEME_PATH/.graphqlconfig
rm -rf $CUSTOM_THEME_PATH/EmptyModule.js
rm -rf $CUSTOM_THEME_PATH/LICENSE
rm -rf $CUSTOM_THEME_PATH/process-core.yml
rm -rf $CUSTOM_THEME_PATH/src/app
rm -rf $CUSTOM_THEME_PATH/src/sw

cat > $CUSTOM_THEME_PATH/README.md << EOF
# Custom theme $1/$2
EOF

cd $CUSTOM_THEME_PATH
npm ci
cd $CWD

showMessage "Add reverse proxy project"
git submodule add --force -b reverse-proxy git@github.com:astik/scandipwa-init-front.git reverse-proxy
cd reverse-proxy
npm ci
cd $CWD

showMessage "Add base-theme for codefallback"
git submodule add --force -b $BASE_THEME_BRANCH $BASE_THEME_URL vendor/scandipwa/source

showMessage "Commit everything as part of initalization"
git commit -m "Inital files, generated by init script"

showMessage "Everything ready, please refer to README.md for the next steps"
